### ISSUE TITLE
Пути на картинках

### ISSUE THREAD

**Issue by critow** [ivanivanov92/learning-project#5]
https://github.com/ivanivanov92/learning-project/blob/4b34c1f6fc5b2d241c4c733fde894c75d85efcb6/index.html#L23

Сделай пути по аналогии как с подключением стилей `Layer_3.jpg` так как они сейчас в одной папке.

**Comment by ivanivanov92** [comment]
<div class=" img1"><img src="./img/Layer_3.jpg" alt="">
